// This file was generated by the XState CLI, please do not edit it manually.
import { assign, createMachine } from 'xstate';

const machine = createMachine(
  {
    context: {
      sun: 0,
      cloud: 0,
      balloon: 0,
      sparkle: 0,
    },
    id: 'Emoji party',
    initial: 'Idle',
    states: {
      Idle: {
        on: {
          sun: {
            target: 'Idle',
            actions: assign({ sun: ({ context }) => context.sun + 1 }),
          },
          cloud: {
            target: 'Idle',
            actions: assign({ cloud: ({ context }) => context.cloud + 1 }),
          },
          balloon: {
            target: 'Idle',
            actions: assign({ balloon: ({ context }) => context.balloon + 1 }),
          },
          sparkle: {
            target: 'Idle',
            actions: assign({ sparkle: ({ context }) => context.sparkle + 1 }),
          },
          reset: {
            target: 'Idle',
            actions: [
              assign({ sun: 0 }),
              assign({ sparkle: 0 }),
              assign({ cloud: 0 }),
              assign({ balloon: 0 }),
            ],
          },
        },
      },
    },
    types: {
      events: {} as
        | { type: 'sun' }
        | { type: 'cloud' }
        | { type: 'reset' }
        | { type: 'balloon' }
        | { type: 'sparkle' },
      context: {} as {
        sun: number;
        cloud: number;
        balloon: number;
        sparkle: number;
      },
    },
  },
  {
    actions: {},
    actors: {},
    guards: {},
    delays: {},
  },
);
export const skyConfig = {
  actorId: '4be484fc-f769-4a89-977c-8ef74925ad13',
  machine,
};
